spring.application.name=echolife-governance-AI-safety

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/echolife
spring.datasource.username=postgres
spring.datasource.password=Gana@9380
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
